import React from 'react';
import { Document, Page, Text, View, StyleSheet, renderToBuffer } from '@react-pdf/renderer';
import type { ResearchResult } from './types';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica', color: '#1a1a2e' },
  headerBar: { marginBottom: 20, borderBottom: '2 solid #3b5bdb', paddingBottom: 12 },
  companyName: { fontSize: 22, fontWeight: 700, color: '#24397f' },
  website: { fontSize: 11, color: '#3b5bdb', marginTop: 2 },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 700,
    marginTop: 18,
    marginBottom: 6,
    color: '#24397f',
  },
  row: { flexDirection: 'row', marginBottom: 4 },
  label: { width: 90, fontWeight: 700, color: '#444' },
  value: { flex: 1 },
  bullet: { flexDirection: 'row', marginBottom: 3 },
  bulletDot: { width: 12 },
  bulletText: { flex: 1 },
  competitorRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
    borderBottom: '0.5 solid #ddd',
  },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#888',
    textAlign: 'center',
    borderTop: '0.5 solid #ddd',
    paddingTop: 6,
  },
});

function ReportDocument({ result }: { result: ResearchResult }) {
  const { company, competitors } = result;
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.headerBar}>
          <Text style={styles.companyName}>{company.name}</Text>
          <Text style={styles.website}>{company.website}</Text>
        </View>

        <Text style={styles.sectionTitle}>Company Overview</Text>
        <Text>{company.summary || 'No summary available.'}</Text>

        <Text style={styles.sectionTitle}>Contact Information</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Phone</Text>
          <Text style={styles.value}>{company.phone || 'Not available'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Address</Text>
          <Text style={styles.value}>{company.address || 'Not available'}</Text>
        </View>

        <Text style={styles.sectionTitle}>Products / Services</Text>
        {company.productsServices.length > 0 ? (
          company.productsServices.map((p, i) => (
            <View style={styles.bullet} key={i}>
              <Text style={styles.bulletDot}>•</Text>
              <Text style={styles.bulletText}>{p}</Text>
            </View>
          ))
        ) : (
          <Text>No product/service data available.</Text>
        )}

        <Text style={styles.sectionTitle}>AI-Generated Pain Points</Text>
        {company.painPoints.length > 0 ? (
          company.painPoints.map((p, i) => (
            <View style={styles.bullet} key={i}>
              <Text style={styles.bulletDot}>•</Text>
              <Text style={styles.bulletText}>{p}</Text>
            </View>
          ))
        ) : (
          <Text>No pain points identified.</Text>
        )}

        <Text style={styles.sectionTitle}>Competitor Analysis</Text>
        {competitors.length > 0 ? (
          competitors.map((c, i) => (
            <View style={styles.competitorRow} key={i}>
              <Text>{c.name}</Text>
              <Text>{c.website}</Text>
            </View>
          ))
        ) : (
          <Text>No competitors identified.</Text>
        )}

        <Text style={styles.footer}>
          Generated by AI Company Research Assistant • {new Date(result.generatedAt).toLocaleString()} •
          Model: {result.modelUsed}
        </Text>
      </Page>
    </Document>
  );
}

export async function generatePdfBuffer(result: ResearchResult): Promise<Buffer> {
  return renderToBuffer(<ReportDocument result={result} />);
}
